function [BW,maskedLABImage] = detectBrightRoad(RGB)
%createMask  Threshold RGB image using auto-generated code from colorThresholder app.
%  [BW,MASKEDRGBIMAGE] = createMask(RGB) thresholds image RGB using
%  auto-generated code from the colorThresholder App. The colorspace and
%  minimum/maximum values for each channel of the colorspace were set in the
%  App and result in a binary mask BW and a composite image maskedRGBImage,
%  which shows the original RGB image values under the mask BW.

% Auto-generated by colorThresholder app on 04-Apr-2016
%------------------------------------------------------


% Convert RGB image to chosen color space
RGB = im2double(RGB);
cform = makecform('srgb2lab', 'AdaptedWhitePoint', whitepoint('D65'));
I = applycform(RGB,cform);

% Define thresholds for channel 1 based on histogram settings
channel1Min = 55.002;
channel1Max = 79.548;

% Define thresholds for channel 2 based on histogram settings
channel2Min = -9.488;
channel2Max = -4.344;

% Define thresholds for channel 3 based on histogram settings
channel3Min = 5.415;
channel3Max = 13.958;

% Create mask based on chosen histogram thresholds
BW = (I(:,:,1) >= channel1Min ) & (I(:,:,1) <= channel1Max) & ...
    (I(:,:,2) >= channel2Min ) & (I(:,:,2) <= channel2Max) & ...
    (I(:,:,3) >= channel3Min ) & (I(:,:,3) <= channel3Max);

% Initialize output masked image based on input image.
maskedLABImage = double(BW);
maskedLABImage(BW~=1) = 0;
maskedLABImage = imgaussfilt(maskedLABImage,2);
maskedLABImage = maskedLABImage./max(max(maskedLABImage));
maskedLABImage = bsxfun(@minus,1,maskedLABImage);


